### ISSUE TITLE
 org.gnome.Platform//42 is end-of-life

### ISSUE THREAD

**Issue by rusty-snake** [flathub/org.gnome.Aisleriot#14]
The GNOME 42 runtime is no longer supported as of March 21, 2023. Please ask your application developer to migrate to a supported platform.

**Comment by jjgalvez** [comment]
Any time table for when this update will be posted to flathub?

**Comment by hfiguiere** [comment]
turns out the build failed.

give it a few hours.

**Comment by jjgalvez** [comment]
Thanks for the reply I'll check again tomorrow  ---- On Mon, 24 Apr 2023 08:15:48 -0400  ***@***.***  wrote ----
turns out the build failed.
give it a few hours.
