### ISSUE TITLE
Remove talk gconf, update to 41

### ISSUE THREAD

**Issue by nedrichards** [flathub/org.gnome.Aisleriot#9]
In #8 we turned off using gconf to save settings but we still have the talk gconf finish arg, it should likely be removed now.

We could also experiment with the 41 runtime.

**Comment by TiZ-HugLife** [comment]
`flatpak update` is now complaining about Aisleriot being on an EOL runtime.

**Comment by hfiguiere** [comment]
Runtime upgrade has been merged.
